package com.example.y.mvp;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table "IMAGE_LIST_INFO".
 */
public class ImageListInfo {

    private Integer tag;
    private Integer id;
    private Integer galleryclass;
    private String title;
    private String img;
    private Integer count;
    private Integer rcount;
    private Integer fcount;
    private Integer size;

    public ImageListInfo() {
    }

    public ImageListInfo(Integer tag) {
        this.tag = tag;
    }

    public ImageListInfo(Integer tag, Integer id, Integer galleryclass, String title, String img, Integer count, Integer rcount, Integer fcount, Integer size) {
        this.tag = tag;
        this.id = id;
        this.galleryclass = galleryclass;
        this.title = title;
        this.img = img;
        this.count = count;
        this.rcount = rcount;
        this.fcount = fcount;
        this.size = size;
    }

    public Integer getTag() {
        return tag;
    }

    public void setTag(Integer tag) {
        this.tag = tag;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getGalleryclass() {
        return galleryclass;
    }

    public void setGalleryclass(Integer galleryclass) {
        this.galleryclass = galleryclass;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getImg() {
        return img;
    }

    public void setImg(String img) {
        this.img = img;
    }

    public Integer getCount() {
        return count;
    }

    public void setCount(Integer count) {
        this.count = count;
    }

    public Integer getRcount() {
        return rcount;
    }

    public void setRcount(Integer rcount) {
        this.rcount = rcount;
    }

    public Integer getFcount() {
        return fcount;
    }

    public void setFcount(Integer fcount) {
        this.fcount = fcount;
    }

    public Integer getSize() {
        return size;
    }

    public void setSize(Integer size) {
        this.size = size;
    }

}
