package com.example.y.mvp;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table "IMAGE_DETAIL_INFO".
 */
public class ImageDetailInfo {

    private Integer tag;
    private Integer id;
    private Integer gallery;
    private String src;

    public ImageDetailInfo() {
    }

    public ImageDetailInfo(Integer tag) {
        this.tag = tag;
    }

    public ImageDetailInfo(Integer tag, Integer id, Integer gallery, String src) {
        this.tag = tag;
        this.id = id;
        this.gallery = gallery;
        this.src = src;
    }

    public Integer getTag() {
        return tag;
    }

    public void setTag(Integer tag) {
        this.tag = tag;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getGallery() {
        return gallery;
    }

    public void setGallery(Integer gallery) {
        this.gallery = gallery;
    }

    public String getSrc() {
        return src;
    }

    public void setSrc(String src) {
        this.src = src;
    }

}
