package com.example.y.mvp;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table "JOKE_TEXT_INFO".
 */
public class JokeTextInfo {

    private Integer tag;
    private String id;
    private String ct;
    private String text;
    private String title;
    private String type;

    public JokeTextInfo() {
    }

    public JokeTextInfo(Integer tag) {
        this.tag = tag;
    }

    public JokeTextInfo(Integer tag, String id, String ct, String text, String title, String type) {
        this.tag = tag;
        this.id = id;
        this.ct = ct;
        this.text = text;
        this.title = title;
        this.type = type;
    }

    public Integer getTag() {
        return tag;
    }

    public void setTag(Integer tag) {
        this.tag = tag;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getCt() {
        return ct;
    }

    public void setCt(String ct) {
        this.ct = ct;
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

}
