package com.example.y.mvp;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table "JOKE_PIC_INFO".
 */
public class JokePicInfoDao extends AbstractDao<JokePicInfo, Integer> {

    public static final String TABLENAME = "JOKE_PIC_INFO";

    public JokePicInfoDao(DaoConfig config) {
        super(config);
    }


    public JokePicInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /**
     * Creates the underlying database table.
     */
    public static void createTable(SQLiteDatabase db) {
        String constraint = "";
        db.execSQL("CREATE TABLE " + constraint + "\"JOKE_PIC_INFO\" (" + //
                "\"TAG\" INTEGER PRIMARY KEY ," + // 0: tag
                "\"ID\" TEXT," + // 1: id
                "\"CT\" TEXT," + // 2: ct
                "\"TITLE\" TEXT," + // 3: title
                "\"TYPE\" TEXT," + // 4: type
                "\"IMG\" TEXT);"); // 5: img
    }

    /**
     * Drops the underlying database table.
     */
    public static void dropTable(SQLiteDatabase db) {
        String sql = "DROP TABLE " + ("IF EXISTS ") + "\"JOKE_PIC_INFO\"";
        db.execSQL(sql);
    }

    @Override
    protected void bindValues(SQLiteStatement stmt, JokePicInfo entity) {
        stmt.clearBindings();

        Integer tag = entity.getTag();
        if (tag != null) {
            stmt.bindLong(1, tag);
        }

        String id = entity.getId();
        if (id != null) {
            stmt.bindString(2, id);
        }

        String ct = entity.getCt();
        if (ct != null) {
            stmt.bindString(3, ct);
        }

        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(4, title);
        }

        String type = entity.getType();
        if (type != null) {
            stmt.bindString(5, type);
        }

        String img = entity.getImg();
        if (img != null) {
            stmt.bindString(6, img);
        }
    }

    @Override
    public Integer readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset) ? null : cursor.getInt(offset);
    }

    @Override
    public JokePicInfo readEntity(Cursor cursor, int offset) {
        return new JokePicInfo( //
                cursor.isNull(offset) ? null : cursor.getInt(offset), // tag
                cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // id
                cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // ct
                cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // title
                cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // type
                cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5) // img
        );
    }

    @Override
    public void readEntity(Cursor cursor, JokePicInfo entity, int offset) {
        entity.setTag(cursor.isNull(offset) ? null : cursor.getInt(offset));
        entity.setId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setCt(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setTitle(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setType(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setImg(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
    }

    @Override
    protected Integer updateKeyAfterInsert(JokePicInfo entity, long rowId) {
        return entity.getTag();
    }

    @Override
    public Integer getKey(JokePicInfo entity) {
        if (entity != null) {
            return entity.getTag();
        } else {
            return null;
        }
    }

    @Override
    protected boolean isEntityUpdateable() {
        return true;
    }

    /**
     * Properties of entity JokePicInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Tag = new Property(0, Integer.class, "tag", true, "TAG");
        public final static Property Id = new Property(1, String.class, "id", false, "ID");
        public final static Property Ct = new Property(2, String.class, "ct", false, "CT");
        public final static Property Title = new Property(3, String.class, "title", false, "TITLE");
        public final static Property Type = new Property(4, String.class, "type", false, "TYPE");
        public final static Property Img = new Property(5, String.class, "img", false, "IMG");
    }

}
