package com.example.y.mvp;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table "NEWS_DETAIL_INFO".
 */
public class NewsDetailInfo {

    private Integer tag;
    private Integer id;
    private Integer count;
    private String description;
    private Integer fcount;
    private String fromname;
    private String img;
    private String keywords;
    private String message;
    private Integer rcount;
    private String title;
    private Integer topclass;
    private String fromurl;
    private Long time;

    public NewsDetailInfo() {
    }

    public NewsDetailInfo(Integer tag) {
        this.tag = tag;
    }

    public NewsDetailInfo(Integer tag, Integer id, Integer count, String description, Integer fcount, String fromname, String img, String keywords, String message, Integer rcount, String title, Integer topclass, String fromurl, Long time) {
        this.tag = tag;
        this.id = id;
        this.count = count;
        this.description = description;
        this.fcount = fcount;
        this.fromname = fromname;
        this.img = img;
        this.keywords = keywords;
        this.message = message;
        this.rcount = rcount;
        this.title = title;
        this.topclass = topclass;
        this.fromurl = fromurl;
        this.time = time;
    }

    public Integer getTag() {
        return tag;
    }

    public void setTag(Integer tag) {
        this.tag = tag;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getCount() {
        return count;
    }

    public void setCount(Integer count) {
        this.count = count;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Integer getFcount() {
        return fcount;
    }

    public void setFcount(Integer fcount) {
        this.fcount = fcount;
    }

    public String getFromname() {
        return fromname;
    }

    public void setFromname(String fromname) {
        this.fromname = fromname;
    }

    public String getImg() {
        return img;
    }

    public void setImg(String img) {
        this.img = img;
    }

    public String getKeywords() {
        return keywords;
    }

    public void setKeywords(String keywords) {
        this.keywords = keywords;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public Integer getRcount() {
        return rcount;
    }

    public void setRcount(Integer rcount) {
        this.rcount = rcount;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public Integer getTopclass() {
        return topclass;
    }

    public void setTopclass(Integer topclass) {
        this.topclass = topclass;
    }

    public String getFromurl() {
        return fromurl;
    }

    public void setFromurl(String fromurl) {
        this.fromurl = fromurl;
    }

    public Long getTime() {
        return time;
    }

    public void setTime(Long time) {
        this.time = time;
    }

}
