package com.example.y.mvp;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table "NEWS_TAB_NAME_INFO".
 */
public class NewsTabNameInfo {

    private Integer tag;
    private Integer id;
    private String name;

    public NewsTabNameInfo() {
    }

    public NewsTabNameInfo(Integer tag) {
        this.tag = tag;
    }

    public NewsTabNameInfo(Integer tag, Integer id, String name) {
        this.tag = tag;
        this.id = id;
        this.name = name;
    }

    public Integer getTag() {
        return tag;
    }

    public void setTag(Integer tag) {
        this.tag = tag;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
